# config/services.yaml
parameters:
    avatars_directory: '%kernel.project_dir%/public/uploads/avatars'
    posts_directory:   '%kernel.project_dir%/public/uploads/posts'

services:
    _defaults:
        autowire:      true
        autoconfigure: true
        bind:
            $avatars_directory:     '%avatars_directory%'
            string $targetDirectory: '%posts_directory%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
